# Generated by Django 5.2.4 on 2025-07-16 10:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_alter_case_options_remove_case_modified_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                help_text="Project description (supports Arabic)",
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
