# Generated by Django 5.2.4 on 2025-07-21 10:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_case_end_date_alter_case_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Project description (supports Arabic)', null=True, verbose_name='Description'),
        ),
    ]
