# Generated by Django 5.2.4 on 2025-07-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_is_archived_alter_case_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='is_archived',
        ),
    ]
