# Generated by Django 5.2.4 on 2025-07-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_alter_projectmanagement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanagement',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
