# Generated by Django 5.2.4 on 2025-07-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_projectmanagement_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmanagement',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
