# Generated by Django 5.2.4 on 2025-07-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_alter_projectmanagement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmanagement',
            options={'ordering': ['-start_date'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='projectmanagement',
            name='is_archived',
        ),
    ]
