# Generated by Django 5.2.4 on 2025-07-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermanagement",
            name="donation_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Set the goal amount in Saudi Riyal",
                max_digits=10,
                null=True,
                verbose_name="Goal Amount (SAR)",
            ),
        ),
    ]
