# Generated by Django 5.2.4 on 2025-07-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order_management", "0002_alter_ordermanagement_donation_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordermanagement",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Donation",
                "verbose_name_plural": "Donations",
            },
        ),
    ]
