# Generated by Django 5.2.4 on 2025-07-21 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_is_archived_alter_case_description'),
        ('order_management', '0002_alter_ordermanagement_options_and_more'),
        ('project_management', '0006_alter_projectmanagement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermanagement',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_donations', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='ordermanagement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_donations', to='project_management.projectmanagement'),
        ),
    ]
