# Generated by Django 5.2.4 on 2025-09-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter advertisement title', max_length=255, verbose_name='Ad Title')),
                ('featured_image', models.ImageField(help_text='Upload advertisement image', upload_to='advertisements/', verbose_name='Featured Image')),
                ('third_party_link', models.URLField(blank=True, help_text='Enter third party URL (optional)', null=True, verbose_name='Third Party Link')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-created_at'],
            },
        ),
    ]
